log_wandb: True
batch_size: 2048
n_layers: 2
n_heads: 4
hidden_size: 256
inner_size: 256
hidden_dropout_prob: 0.1
attn_dropout_prob: 0.1
hidden_act: gelu
mask_ratio: 0.15
loss_type: CE
intermediate_size: 256
num_attention_heads: 2
num_hidden_layers: 2
optimizer: adam

epochs: 100
train_batch_size: 1024
learner: adam
learning_rate: 0.001
train_neg_sample_args:
eval_step: 1
weight_decay: 0.0
loss_decimal_place: 4
metrics: ['Recall', 'NDCG'] 
topk: [1, 10, 50, 100] 
valid_metric: 'NDCG@10' 
eval_args:
  split: {'RS': [0.8, 0.1, 0.1]}  
  mode: 'full' 
  group_by_user: True  
  order: 'TO'
