# env
seed: 42
shuffle: True
reproducibility: True
# NOTE: reproducibility can set to False to accelerate for CNN models like 
# Caser. It has no significant effect on the performance of the model, but 
# sacrifices the reproducibility of the results. We set it to False in the 
# following experiment: 
# - Caser_ml-1m

# dataset info
dataset: 
data_path: /data/group_data/cx_group/REC/data
load_col:
    inter: [user_id, item_id, rating, timestamp]
    item: ['item_id','movie_title','release_year','genre']
USER_ID_FIELD: user_id
ITEM_ID_FIELD: item_id
RATING_FIELD: rating
TIME_FIELD: timestamp
MAX_ITEM_LIST_LENGTH: 50

# filtering 
val_interval: ~
filter_inter_by_user_or_item: True
user_inter_num_interval: "[20,inf)"
item_inter_num_interval: "[20,inf)"


